/**
 * 使用在线占位图片服务的模拟数据
 */

export const MOCK_COURSES_PLACEHOLDER = [
  {
    id: '1',
    title: 'Web前端开发基础',
    description: '学习HTML, CSS和JavaScript的基础知识，构建响应式网页。',
    category: '前端开发',
    status: 'published',
    enrolledStudents: 156,
    progress: 100,
    coverImage: 'https://via.placeholder.com/300x200?text=Web前端开发',
    teacherName: '李明',
    teacherAvatar: 'https://via.placeholder.com/80x80?text=李明',
    level: '入门',
    price: 299,
    isFree: false,
    createdAt: '2023-05-01',
    publishedAt: '2023-05-10',
  },
  {
    id: '2',
    title: 'React高级组件设计',
    description: '深入理解React组件设计模式，学习高阶组件、Hooks等高级概念。',
    category: '前端开发',
    status: 'published',
    enrolledStudents: 78,
    progress: 100,
    coverImage: 'https://via.placeholder.com/300x200?text=React高级组件',
    teacherName: '张华',
    teacherAvatar: 'https://via.placeholder.com/80x80?text=张华',
    level: '高级',
    price: 499,
    isFree: false,
    createdAt: '2023-06-15',
    publishedAt: '2023-06-25',
  },
  {
    id: '3',
    title: 'Node.js后端开发',
    description: '使用Node.js和Express框架构建RESTful API和Web应用。',
    category: '后端开发',
    status: 'published',
    enrolledStudents: 42,
    progress: 80,
    coverImage: 'https://via.placeholder.com/300x200?text=Node.js开发',
    teacherName: '王刚',
    teacherAvatar: 'https://via.placeholder.com/80x80?text=王刚',
    level: '中级',
    price: 399,
    isFree: false,
    createdAt: '2023-07-10',
    publishedAt: '2023-07-20',
  },
  {
    id: '4',
    title: 'Python数据分析',
    description: '学习使用Python进行数据清洗、分析和可视化。',
    category: '数据科学',
    status: 'draft',
    enrolledStudents: 0,
    progress: 60,
    coverImage: 'https://via.placeholder.com/300x200?text=Python数据分析',
    teacherName: '刘芳',
    teacherAvatar: 'https://via.placeholder.com/80x80?text=刘芳',
    level: '中级',
    price: 349,
    isFree: false,
    createdAt: '2023-08-05',
    publishedAt: null,
  },
  {
    id: '5',
    title: '移动应用开发基础',
    description: '了解原生和跨平台移动应用开发的基础知识。',
    category: '移动开发',
    status: 'published',
    enrolledStudents: 65,
    progress: 100,
    coverImage: 'https://via.placeholder.com/300x200?text=移动应用开发',
    teacherName: '陈静',
    teacherAvatar: 'https://via.placeholder.com/80x80?text=陈静',
    level: '入门',
    price: 0,
    isFree: true,
    createdAt: '2023-09-01',
    publishedAt: '2023-09-10',
  },
  {
    id: '6',
    title: '云计算与DevOps',
    description: '学习云服务、容器化和CI/CD流程，实现自动化部署。',
    category: '云计算',
    status: 'published',
    enrolledStudents: 37,
    progress: 90,
    coverImage: 'https://via.placeholder.com/300x200?text=云计算与DevOps',
    teacherName: '赵明',
    teacherAvatar: 'https://via.placeholder.com/80x80?text=赵明',
    level: '高级',
    price: 599,
    isFree: false,
    createdAt: '2023-10-05',
    publishedAt: '2023-10-15',
  }
];
